title: Sophie Stadler
markdown: kramdown
url: http://sophiestadler.com
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
    title: Notes
  soft_computer:
    output: true
    permalink: /softcomputer/:path/
    title: Soft Computer